namespace verhaal;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Australisch zonnebrandschandaal breidt zich uit: opnieuw crèmes uit de schappen Deel dit artikel In Australië verdwijnen steeds meer zonnebrandcrèmes uit de schappen vanwege zorgen over de beschermende werking. Inmiddels zijn in totaal achttien producten niet langer te koop in het land dat kampt met het hoogste percentage huidkankerdiagnoses in de wereld. Australië kent zeer strenge regels voor zonnebrandmiddelen, maar die bleken niet waterdicht. Het zonnebrandschandaal kwam begin deze zomer aan het licht, toen omroep ABC ontdekte dat een aantal populaire, prijzige zonnebrandcrèmes niet de bescherming boden die de producenten beloofden. Eén crème kwam in de test niet verder dan factor 4, terwijl de verpakking gebruikers een bescherming met factor 50+ in het vooruitzicht stelde. Het bedrijf riep de crème daarop terug. Naar aanleiding van die bevindingen stelde de Australische geneesmiddelenautoriteit een onderzoek in. Dat waarschuwt nu voor nog eens zon twintig zonnebrandcrèmes, die dezelfde basisformule hanteren. Uit voorlopige testen blijkt dat het onwaarschijnlijk is dat deze basisformule een beschermingsfactor hoger dan 21 heeft, schrijft de Therapeutic Goods Administration (TGA). Sommige producten komen zelfs niet verder dan factor 4. Van de producten waar de geneesmiddelenautoriteit zich nu zorgen over maakt, zijn er inmiddels acht teruggeroepen of niet langer in productie. Tien andere producten zijn voorlopig niet te koop. Naar twee middelen loopt het onderzoek nog. Eén product wordt wel in Australië gemaakt, maar daar niet verkocht. Correspondent Australië Meike Wijers Dat er nóg meer zonnebrandcrèmes niet de beloofde bescherming bieden, zorgt voor veel ophef in Australië. Dit land wordt ook wel de huidkankerhotspot van de wereld genoemd. Nergens ter wereld komt huidkanker zo vaak voor als hier; naar verwachting krijgen twee op de drie Australiërs in hun leven een vorm van huidkanker. Niet voor niets groeien Australiërs op met talloze waarschuwingen om zich tegen de zon te beschermen. Zonnebrand is daar een essentieel onderdeel van, en wordt daarom gereguleerd als een medisch product. Verder onderzoek volgt nog. Mogelijk volgen boetes voor de bedrijven. Het zonnebrandschandaal kwam voor veel Australiërs als een schok, maar de bevindingen kunnen volgens deskundigen ook wereldwijd gevolgen hebben. Zo blijken er problemen te zijn met de productie van sommige crèmes en zijn er vraagtekens te plaatsen bij de betrouwbaarheid van laboratoriumtests die de beschermingsfactor van een crème bepalen. De producent van de veel minder krachtige basisformule is inmiddels gestopt met het maken van de crème, laat de TGA weten. Met filmpjes als deze, die kinderen eraan herinnert buiten een hoed, shirt en zonnebrand te gebruiken, wijst de Australische Cancer Council al decennia op de risico's van zonneschijn:");
    }
}
